---

- name: add docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: '0644'

- name: install docker packages
  yum:
    name: "{{ docker_packages_install | join(',') }}"
    state: present

- name: enable and start docker service
  systemd:
    name: docker
    state: started
    enabled: yes
