---

- name: check package exist
  package_facts:
    manager: auto

- name: Remove Old Docker Packages
  yum:
    name: "{{ docker_packages_remove | join(',') }}"
    state: absent

- name: add docker repo
  get_url:
    url: "{{ docker_repo_url }}"
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: '0644'

- name: install docker packages
  yum:
    name: "{{ docker_packages_install | join(',') }}"
    state: present

- name: enable and start docker service
  systemd:
    name: docker
    state: started
    enabled: yes

- name: uname -s
  command: uname -s
  register: uname_s

- name: uname -m
  command: uname -m
  register: uname_m

- name: install docker-compose binary
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ uname_s.stdout }}-{{ uname_m.stdout }}"
    dest: "{{ docker_compose_binary_path }}"
    mode: '0644'

- name: give permission to docker-compose
  file:
    path: "{{ docker_compose_binary_path }}"
    owner: root
    group: root
    mode: '+x'

- name: create a symbolic link
  file:
    src: "{{ docker_compose_binary_path }}"
    dest: "/usr/bin/docker-compose"
    owner: root
    group: root
    state: link
